GET http://localhost:8080/contacts HTTP/1.1
###
POST http://localhost:8080/contacts HTTP/1.1
### That POST only creates an _id when I test it
DELETE http://localhost:8080/contacts/651793fa740e794e8e475fe0 HTTP/1.1

### POST Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json 
### content-type goes below POST line

{
    "firstName": "Contact",
    "lastName" : "Example",
    "email" : "user@example.com",
    "favoriteColor" : "red",
    "birthday" : "09/30/2023"
}

### Render
GET https://cse-341-vtdf.onrender.com/contacts HTTP/1.1
### Api Docs deployed in Render
GET https://cse-341-vtdf.onrender.com/api-docs HTTP/1.1